config/routes.rb
Rails.application.routes.draw do
  resources :siblings, only: [:index] do
    member do
      post "deploy"
    end
  end

  get "siblings/instructions" => "siblings/instructions#index", as: :siblings_instructions
  get "siblings/deploys" => "siblings/deploys#index", as: :siblings_deploys

  post "webhooks/g5-configurator" => "webhooks#g5_configurator", as: :g5_configurator_webhook
end

app/models/sibling.rb
class Sibling < ActiveRecord::Base
  has_many :deploys
  has_many :instructions, through: :deploys

  validates :uid, presence: true, uniqueness: true
  validates :name, presence: true
  validates :git_repo, presence: true
  validates :heroku_repo, presence: true
  validates :heroku_app_name, presence: true

  class << self
    def main_app_uid
      ENV["MAIN_APP_UID"]
    end

    def main_app_hcard
      Microformats2.parse(main_app_uid).card
    end

    def consume_main_app_hcard
      main_app_hcard.g5_siblings.map do |sibling|
        find_or_create_from_hcard(sibling.format)
      end.compact if main_app_hcard
    rescue OpenURI::HTTPError => e
      raise e unless /304 Not Modified/ =~ e.message
    end

    def async_consume
      Resque.enqueue(SiblingConsumer)
    end

    def find_or_create_from_hcard(hcard)
      find_or_create_by(uid: hcard.uid.to_s) do |sibling|
        sibling.name = hcard.name.to_s
        sibling.git_repo = hcard.g5_git_repo.to_s
        sibling.heroku_repo = hcard.g5_heroku_repo.to_s
        sibling.heroku_app_name = hcard.g5_heroku_app_name.to_s
      end
    end

    def deploy_all(manual=true, instruction_id=nil)
      all.each { |sibling| sibling.deploy(instruction_id) }
    end

    def deploy_some(kinds=[], instruction_id=nil)
      apps = kinds.flat_map { |k| Sibling.where('name LIKE ?', "%-#{k}-%") }
      apps.each { |sibling| sibling.deploy(instruction_id) }
    end
  end

  def deploy(instruction_id=nil)
    self.deploys.create!(
      instruction_id: instruction_id,
      manual: !instruction_id,
      git_repo: git_repo,
      heroku_repo: heroku_repo,
      heroku_app_name: heroku_app_name
    )
  end
end

app/models/sibling/deploy.rb
class Sibling::Deploy < ActiveRecord::Base

  belongs_to :sibling
  belongs_to :instruction

  validates :sibling_id, presence: true
  validates :manual, inclusion: { in: [true, false] }
  validates :git_repo, presence: true
  validates :heroku_repo, presence: true
  validates :heroku_app_name, presence: true

  after_create :async_deploy

  state_machine :initial => :new do
    event :queue do
      transition any => :queued
    end
    event :start do
      transition any => :deploying
    end
    event :fail do
      transition any => :failed
    end
    event :succeed do
      transition any => :succeeded
    end
  end

  scope :manual, -> { where(manual: true) }
  scope :automatic, -> { where(manual: false) }

  def deploy
    start!

    GithubHerokuDeployer.deploy(deployer_options)
    GithubHerokuDeployer.heroku_run("rake db:migrate", deployer_options)

    succeed!
  rescue StandardError => e
    fail!
    raise e
  end

  def deployer_options
    { github_repo: git_repo,
      heroku_repo: heroku_repo,
      heroku_app_name: heroku_app_name }
  end

  def async_deploy
    queue!
    Resque.enqueue(SiblingDeployer, self.id)
  rescue StandardError => e
    fail!
    raise e
  end
end

app/models/sibling/instruction.rb
require 'open-uri'

class Sibling::Instruction < ActiveRecord::Base

  has_many :deploys
  has_many :siblings, through: :deploys

  validates :uid, uniqueness: true
  validates :name, presence: true
  validates :published_at, presence: true

  after_save :deploy

  class << self
    def feed_url
      ENV["G5_CONFIGURATOR_FEED_URL"]
    end

    def feed
      Microformats2.parse(feed_url)
    end

    def consume_feed
      feed.entries.map do |hentry|
        find_or_create_from_hentry(hentry) if targets_me?(hentry)
      end.compact
    rescue OpenURI::HTTPError => e
      raise e unless /304 Not Modified/ =~ e.message
    end

    def async_consume_feed
      Resque.enqueue(SiblingInstructionConsumer)
    end

    def targets_me?(hentry)
      targets = instruction(hentry).g5_targets.map { |t| t.format.uid.to_s }
      targets && targets.include?(Sibling.main_app_uid)
    end

    def instruction(hentry)
      Microformats2.parse(hentry.content.to_s).card
    end

    def find_or_create_from_hentry(hentry)
      find_or_create_by(uid: hentry.uid.to_s) do |instruction|
        hcard = instruction(hentry)
        instruction.name = hcard.name.to_s
        instruction.published_at = hentry.updated.value
        if hentry.try(:g5_updated_app_kinds).present?
          instruction.updated_app_kinds = hentry.g5_updated_app_kinds.map(&:to_s)
        end
      end
    end
  end # class << self

  private

  def deploy
    Sibling.deploy_some(self.updated_app_kinds, self.id)
  end
end

app/controllers/siblings/application_controller.rb
class Siblings::ApplicationController < ApplicationController
end

app/controllers/siblings/deploys_controller.rb
class Siblings::DeploysController < Siblings::ApplicationController
  def index
    @siblings_deploys = Sibling::Deploy.order("created_at DESC")
  end
end

app/controllers/siblings/instructions_controller.rb
class Siblings::InstructionsController < Siblings::ApplicationController
  def index
    @siblings_instructions = Sibling::Instruction.order("created_at DESC")
  end
end

app/controllers/siblings_controller.rb
class SiblingsController < ApplicationController
   def index
     @siblings = Sibling.all
   end

   def deploy
     @sibling = Sibling.find(params[:id])
     if @sibling.deploy
       redirect_to siblings_deploys_path, notice: "Deploy has been queued."
     else
       redirect_to siblings_deploys_path, alert: "Something went wrong. Deploy has not been queued."
     end
   end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  def g5_configurator
    Sibling::Instruction.async_consume_feed
    render json: {}, status: :ok
  end
end

app/views/siblings/_nav.html.erb
<ul class="nav nav-pills">
  <li class="<%= page == :siblings ? "active" : nil%>"><%= link_to "Siblings", siblings_path %></li>
  <li class="<%= page == :instructions ? "active" : nil%>"><%= link_to "Instructions", siblings_instructions_path %></li>
  <li class="<%= page == :deploys ? "active" : nil%>"><%= link_to "Deploys", siblings_deploys_path %></li>
</ul>

app/views/siblings/deploys/index.html.erb
<% title "Deploys" %>

<%= render partial: "siblings/nav", locals: { page: :deploys } %>

<table class="table table-striped">
  <thead>
    <tr>
      <td>Id</td>
      <td>Created at</td>
      <td>Heroku app name</td>
      <td>State</td>
      <td>Git repo</td>
      <td>Heroku Repo</td>
      <td>Sibling id</td>
      <td>Instruction id</td>
      <td>Manual</td>
    </tr>
  </thead>
  <tbody>
    <% @siblings_deploys.each do |t| %>
      <tr>
        <td><%= t.id %></td>
        <td><%= t.created_at %></td>
        <td><%= t.heroku_app_name %></td>
        <td><%= t.state %></td>
        <td><%= t.git_repo %></td>
        <td><%= t.heroku_repo %></td>
        <td><%= t.sibling_id %></td>
        <td><%= t.instruction_id %></td>
        <td><%= t.manual %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/siblings/index.html.erb
<% title "Siblings" %>

<%= render partial: "siblings/nav", locals: { page: :siblings } %>

<table class="table table-striped">
  <thead>
    <tr>
      <td>Id</td>
      <td>Name</td>
      <td>Heroku app name</td>
      <td>Git repo</td>
      <td>Heroku repo</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <% @siblings.each do |t| %>
      <tr>
        <td><%= t.id %></td>
        <td><%= t.name %></td>
        <td><%= t.heroku_app_name %></td>
        <td><%= t.git_repo %></td>
        <td><%= t.heroku_repo %></td>
        <td>
          <%= link_to 'UID', t.uid, class: "btn" %>
          <% unless t.main_app? %>
            <%= link_to "Deploy", deploy_sibling_path(t), class: "btn", method: :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/siblings/instructions/index.html.erb
<% title "Instructions" %>

<%= render partial: "siblings/nav", locals: { page: :instructions } %>

<table class="table table-striped">
  <thead>
    <tr>
      <td>Id</td>
      <td>Name</td>
      <td>Published at</td>
      <td>Created at</td>
      <td>Actions</td>
    </tr>
  </thead>
  <tbody>
    <% @siblings_instructions.each do |t| %>
      <tr>
        <td><%= t.id %></td>
        <td><%= t.name %></td>
        <td><%= t.published_at %></td>
        <td><%= t.created_at %></td>
        <td>
          <%= link_to 'UID', t.uid, class: "btn" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>